### ISSUE TITLE
Install environment

### ISSUE THREAD

**Issue by W-D0n** [OpenClassrooms-Student-Center/Billed-app-FR-Back#3]
I tried to follow guidelines to install the project environment (notice that i'm not enough familiar with all stuff like npm/node etc...).

After the git clone of back-end

npm install :
![image](https://user-images.githubusercontent.com/71557306/146771819-77e77476-4651-483c-b1a6-749d5157de31.png)

npm run:dev
![image](https://user-images.githubusercontent.com/71557306/146771893-c803e3dc-b7e5-4d5d-8f95-1f2c10db6fab.png)

npm run run:dev
![image](https://user-images.githubusercontent.com/71557306/146771948-660ccf14-6da9-4a32-bf64-281fb58dddeb.png)

"run run:dev" because package.json contains :
![image](https://user-images.githubusercontent.com/71557306/146771991-df9b9f34-6fcc-470a-b56e-8d1595529020.png)

npm : 6.14.11
node :v14.16.0

**Comment by youlijie** [comment]
same problem

**Comment by W-D0n** [comment]
> same problem

It seems to be an issue with windows system.
Try to use this command : `node server.js` (it worked for me).

I did this :
![image](https://user-images.githubusercontent.com/71557306/148028675-41665faf-b7a9-4256-8a13-ab71ca45a667.png)

**Comment by thxDuck** [comment]
Hi !
I have found the solution from stack-overflow : https://stackoverflow.com/questions/11928013/node-env-is-not-recognized-as-an-internal-or-external-command-operable-comman

`npm install -g win-node-env`

It works for me, I hope it works for you !

**Comment by W-D0n** [comment]
Nice, i didn't dig much further.
My command worked for me though :)

One more solution is better.

**Comment by charlesVeneau** [comment]
None of the two solutions works for me.

npm run run:dev/
![image](https://user-images.githubusercontent.com/47984439/149676114-59e8a374-e637-498b-add9-3b771a286915.png)


If found a solution because it's coming from the auth.js file in the middlewares folder.
The user const call the userPayload variable with ? as reference. delete the two ? and you are good

**Comment by charlesVeneau** [comment]
> None of the two solutions works for me.
> 
> npm run run:dev/ ![image](https://user-images.githubusercontent.com/47984439/149676114-59e8a374-e637-498b-add9-3b771a286915.png)
> 
> If found a solution because it's coming from the auth.js file in the middlewares folder. The user const call the userPayload variable with ? as reference. delete the two ? and you are good

I'm a bit concerne as these issue is originally dated form Novembre the 15th and hasn't been fixed since.

**Comment by Reimhinn** [comment]
Thank you !

**Comment by ultimecreation** [comment]
Hi all, i also faced this issue and solved it by using npm cross-env package (npm install --save-dev cross-env)
 => https://github.com/kentcdodds/cross-env



![crossenv](https://user-images.githubusercontent.com/34138024/180575961-134db16f-1b40-4e1a-9866-b8c4d62f7cb6.PNG)

**Comment by W-D0n** [comment]
Thanks for your reply.
I think i can close this issue.
